### ISSUE TITLE
Adding a new cluster node resets the Azure Security Groups

### ISSUE THREAD

**Issue by rvvincelli** [hortonworks/cloudbreak#3071]
The security groups are wiped out when adding and possibly removing a cluster node with the up/down scale UI wizard.

- `cbd version`: `local version:1.16.4`
- Host platform: Azure
- No particular logging, the firewalls are just reset to the Cloudbreak defaults for Azure (0.0.0.0 allowed on 22, 443, 9443)
- To reproduce:
  - create a cluster
  - edit the security group
  - add a new node via the UI wizard
  - check the security group again: your changes are gone

FYI @ksheytanov @rtodorova

**Comment by mhmxs** [comment]
Hi @rvvincelli ,

`edit the security group` You mean edit security group on Azure portal? That happens because Cloudbreak uses a template to describe the underlaying architecture, and when you up or downscale the cluster, it resends the template and Azure eliminates everything what is missing from the template. Works as design. There are workarounds but you have to update database manually what i can't suggest calm hearth.

**Comment by rvvincelli** [comment]
@mhmxs @doktoric This happened also with predefined security groups for the templates. Actually I would suggest to pay more attentions to such scenarios. For example, more often than not one does not know all the firewall entries in advance, so they are added as the deployment goes on. As an adopter one of the few plus points of Cloudbreak is to instrument, scale, fix easily - "by design" without warnings whatsoever is definitely not a pro for a production like perspective. Thanks,
